//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LWALDTECH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerWorkstation
    {
        public int CustomerID { get; set; }
        public string WorkstationName { get; set; }
        public string WorkstationIPAddress { get; set; }
        public string WorkstationOS { get; set; }
        public int WorkstationID { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
